### PR TITLE
Use Brewfile

### PR DESCRIPTION
**Pull request by Lutzifer**
If a project needs a brew dependency, e.g. rbenv, n or elixir

it should add it to its brewfile

### CODE REVIEW

**Review by ddengler — CHANGES_REQUESTED** [review]
can we detect the brew requirement for the other steps and error if not found? Example: "rbenv is not installed. please add it as a dependency to your brewfile and run bootstrap again"

**Comment by Lutzifer** [comment]
> can we detect the brew requirement for the other steps and error if not found? Example: "rbenv is not installed. please add it as a dependency to your brewfile and run bootstrap again"

Personally I am on the "not worth it" side for this, as all participants should be simply made aware, that everything needed from brew should go to the Brewfile. But we can add it as guidance if it is seen as necessarry.

**Comment by aspala** [comment]
Can we add a sample brewfile?

Cann we add a script which migrates existing installation by running through all checks in the bootstrap file and creates a sample brewfile if not exists?

pseudo:
```pseudo
return if exist brewfile

touch brewfile

if -e ruby-version do
  "rbenv\n" > brewfile
  "ruby-build\n" > brewfile
end


if -e .node-version do
  "n\n" > brewfile
end
```

**Comment by Lutzifer** [comment]
Sample Brewfile: 👍

Migration Script: I think this is more hassle, than simply converting the project by Hand.

**Comment by aspala** [comment]
I am fine with the change in general

I think i missunderstood the whole problem. What i need is an extractor-script, which **once** extracts the project's dependencies into a brewfile.

This is because the bootstrapping process now fails (does not install anything and/or tries to install ruby version without previously installing correct ruby-build etc.), if no brewfile had been previously created.
All i wanna do, is to simplify the process of creating that brewfile, as we do not know when we will upgrade our projects to the new bootstrap.

**Comment by Lutzifer** [comment]
> I am fine with the change in general
> 
> I think i missunderstood the whole problem. What i need is an extractor-script, which **once** extracts the project's dependencies into a brewfile.
> 
> This is because the bootstrapping process now fails (does not install anything and/or tries to install ruby version without previously installing correct ruby-build etc.), if no brewfile had been previously created.
> All i wanna do, is to simplify the process of creating that brewfile, as we do not know when we will upgrade our projects to the new bootstrap.

Just use this Brewfile and delete everything the project does not need when upgrading a project:

```
tap "homebrew/bundle"

brew "elixir"
brew "git-lfs"
brew "n"
brew "openconnect"
brew "protobuf"
brew "rbenv"
```

**Comment by aspala** [comment]
Changes fine with me.

**Review by aspala — APPROVED** [review]

**Review by aspala — APPROVED** [review]

**Pull request merged**
